[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "tiny-sota"
version = "0.0.3"
authors = [
  { name="Marvin Mboya", email="marvindesmond@gmail.com" },
]

description = "optimize SOTA models to the hardware architectures for optimal low-latency inferencing"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: System :: Distributed Computing"
]

license-files = ["LICEN[CS]E*"]

dependencies = [
  'torch',
  'torchvision',
  'torchaudio',
  'safetensors',
  'huggingface_hub[cli]',
  'tokenizers',
  'tiktoken',
  'requests'
]

[project.optional-dependencies]
# pip install tiny-sota[tts]
tts = ["soundfile", "misaki", "spacy", "num2words", "phonemizer-fork", "espeakng-loader"]

[project.urls]
Homepage = "https://github.com/marvinmboya/tiny-sota"
Issues = "https://github.com/marvinmboya/tiny-sota/issues"
repository = "https://github.com/marvinmboya/tiny-sota"
